{% set name = "griffe-inherited-docstrings" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/griffe_inherited_docstrings-{{ version }}.tar.gz
  sha256: d179b6a6b7dc260fb892ad5b857837afd6f9de6193fc26d14463c4e9975a0cd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - griffe >=0.49

test:
  imports:
    - griffe_inherited_docstrings
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/griffe-inherited-docstrings
  summary: Griffe extension for inheriting docstrings.
  license: ISC
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/griffe-inherited-docstrings/

extra:
  recipe-maintainers:
    - thomasmarwitz
